### ISSUE TITLE
Tibetan characters do not display properly on the profile card generation

### ISSUE THREAD

**Issue by Phundrak** [kernelconcept/kernel-bot#2]
If possible maybe the font could change when Tibetan characters are encountered.
Fonts suggested:
ttf-tibetan-uni
One of Lobsang Monlam 3’s fonts (one of the Uchen font)
Tibetan machine uni

**Comment by afranche** [comment]
I'm sorry about the problem. The font is responsible for this so we might get a fallback font if Pillow permits it. For the moment, I'm gonna close this so we can open a general Unicode issue for every languages (Cyrillic etc ...)
